title: solidpixel
subtitle: Real-time rendering adventures

description: >-
  Some technical ramblings on real-time graphics, texture compression,
  optimization and performance analysis tools.

copyyears: "2019-2021"
author: solidpixel
avatar: assets/images/avatar.jpg

baseurl: ""
url: "https://solidpixel.github.io"

github_url: https://github.com/solidpixel
twitter_url: https://twitter.com/thesolidpixel

remote_theme: chrisbobbe/jekyll-theme-prologue
collections: [sections]
